from franquenstein.being import Being

being = Being()
TRAINING_CORPUS = {
    'naturaleza': [
        'El sol es una estrella que da luz y calor a la Tierra',
        'La luna refleja la luz del sol y tiene fases',
        'Los árboles producen oxígeno a partir de la luz solar',
        'El agua de los ríos viene de la lluvia y va al mar',
        'Las estaciones del año son primavera, verano, otoño e invierno',
        'Las montañas se forman por el movimiento de placas tectónicas',
        'El viento mueve las nubes y las semillas de las plantas',
        'Los volcanes expulsan lava desde el interior de la Tierra',
        'El arcoíris aparece cuando la luz del sol atraviesa gotas de lluvia',
        'Las mareas suben y bajan por la gravedad de la luna',
    ],
    'animales': [
        'Los perros son animales leales que viven con los humanos',
        'Los gatos son independientes y cazan ratones',
        'Las ballenas son los animales más grandes del planeta',
        'Las abejas polinizan las flores y producen miel',
        'Los delfines son mamíferos inteligentes que viven en el mar',
        'Las águilas vuelan alto y tienen una vista extraordinaria',
        'Los elefantes tienen buena memoria y viven en manadas',
        'Los pulpos tienen ocho tentáculos y son muy inteligentes',
        'Las hormigas trabajan en equipo y construyen colonias enormes',
        'Los caballos son rápidos y han sido compañeros del ser humano',
    ],
    'ciencia': [
        'La gravedad es la fuerza que mantiene los planetas en órbita',
        'Los átomos son las partículas básicas que forman toda la materia',
        'La energía no se crea ni se destruye, solo se transforma',
        'La velocidad de la luz es la más rápida del universo',
        'El ADN contiene las instrucciones genéticas de los seres vivos',
        'Los electrones giran alrededor del núcleo del átomo',
        'La fotosíntesis convierte la luz solar en energía para las plantas',
        'El sonido viaja más rápido en el agua que en el aire',
        'Los planetas del sistema solar giran alrededor del sol',
        'Las células son la unidad básica de la vida',
    ],
    'emociones': [
        'La alegría es sentir felicidad por algo bueno que pasa',
        'La tristeza es una emoción que nos ayuda a procesar la pérdida',
        'El miedo nos protege de peligros y nos hace estar alerta',
        'La curiosidad nos impulsa a explorar y aprender cosas nuevas',
        'El amor es un sentimiento profundo de conexión con otros',
        'La sorpresa ocurre cuando algo inesperado sucede',
        'La calma nos permite pensar con claridad y tomar buenas decisiones',
        'La frustración aparece cuando no logramos lo que queremos',
        'La gratitud es valorar lo bueno que tenemos en la vida',
        'La empatía es entender cómo se sienten los demás',
    ],
    'tecnologia': [
        'Los ordenadores procesan información usando ceros y unos',
        'Internet conecta millones de ordenadores en todo el mundo',
        'Python es un lenguaje de programación popular y versátil',
        'La inteligencia artificial aprende de los datos que recibe',
        'Los robots pueden hacer tareas repetitivas con precisión',
        'Las bases de datos almacenan información de forma organizada',
        'Los algoritmos son instrucciones paso a paso para resolver problemas',
        'El código fuente son las instrucciones que entienden los ordenadores',
        'La nube permite guardar datos en servidores remotos',
        'Las redes neuronales artificiales se inspiran en el cerebro humano',
    ],
    'filosofia': [
        'Pensar es lo que nos hace conscientes de nuestra existencia',
        'La ética estudia lo que está bien y lo que está mal',
        'La libertad es poder elegir nuestras propias acciones',
        'La verdad puede ser difícil de encontrar pero siempre vale la pena',
        'La identidad es lo que nos hace únicos como individuos',
        'El tiempo pasa para todos pero cada uno lo percibe diferente',
        'Aprender de los errores es una forma de crecer',
        'La consciencia es saber que existes y que piensas',
        'Las preguntas son más importantes que las respuestas',
        'La creatividad es conectar ideas que parecen no relacionarse',
    ],
    'musica': [
        'La música es sonido organizado que transmite emociones',
        'El ritmo es la base de toda composición musical',
        'Las notas musicales son do re mi fa sol la si',
        'Los instrumentos de cuerda vibran para producir sonido',
        'Una melodía es una secuencia de notas que forma una idea musical',
        'La armonía es cuando varias notas suenan bien juntas',
        'El piano tiene teclas blancas y negras que producen diferentes notas',
        'La guitarra es uno de los instrumentos más populares del mundo',
        'Cantar es usar la voz como instrumento musical',
        'La música puede cambiar nuestro estado de ánimo rápidamente',
    ],
    'matematicas': [
        'Los números son herramientas para contar y medir cosas',
        'La suma es juntar cantidades para obtener un total',
        'La multiplicación es una forma rápida de sumar varias veces',
        'La geometría estudia las formas y el espacio',
        'Las fracciones representan partes de un todo',
        'Pi es un número que relaciona el diámetro con la circunferencia',
        'La probabilidad mide las posibilidades de que algo ocurra',
        'Los patrones matemáticos aparecen en la naturaleza constantemente',
        'Las ecuaciones son como balanzas que deben estar equilibradas',
        'El cero representa ausencia de cantidad',
    ],
    'historia': [
        'Los dinosaurios vivieron hace millones de años antes que los humanos',
        'La escritura se inventó hace más de cinco mil años',
        'Las pirámides de Egipto fueron construidas como tumbas para faraones',
        'La imprenta permitió difundir los libros a mucha más gente',
        'La revolución industrial cambió la forma de fabricar y trabajar',
        'Los mapas antiguos mostraban el mundo de forma diferente al real',
        'El fuego fue uno de los primeros descubrimientos de la humanidad',
        'Las civilizaciones antiguas construyeron grandes ciudades y monumentos',
        'Los viajes de exploración conectaron continentes',
        'La democracia nació en la antigua Grecia',
    ],
    'cuerpo_humano': [
        'El cerebro controla todo lo que hacemos pensamos y sentimos',
        'El corazón bombea sangre a todo el cuerpo sin parar',
        'Los pulmones toman oxígeno del aire y expulsan dióxido de carbono',
        'Los huesos dan estructura al cuerpo y protegen los órganos',
        'Los músculos permiten el movimiento del cuerpo',
        'La piel es el órgano más grande del cuerpo humano',
        'Los ojos captan la luz y la convierten en imágenes',
        'Las neuronas transmiten señales eléctricas por todo el cuerpo',
        'Dormir es necesario para que el cerebro procese información',
        'El sistema inmunológico defiende el cuerpo de enfermedades',
    ],
    'relaciones': [
        'La amistad se basa en confianza y cariño',
        'La familia es el primer grupo social',
        'Escuchar es tan importante como hablar',
        'El respeto es valorar a los demás',
        'La comunicación clara evita malentendidos',
        'La confianza se construye con tiempo',
        'Pedir perdón es valentía y madurez',
        'Compartir hace experiencias significativas',
        'La diversidad enriquece comunidades',
        'Los límites sanos son necesarios en toda relación',
    ],
    'alimentacion': [
        'Las frutas y verduras contienen vitaminas esenciales',
        'El agua es fundamental para la vida',
        'Los cereales dan energía al cuerpo',
        'Las proteínas ayudan a construir y reparar músculos',
        'Cocinar transforma ingredientes en alimentos',
        'La sal y el azúcar deben consumirse con moderación',
        'El yogur tiene bacterias beneficiosas',
        'El chocolate se hace con cacao',
        'Una dieta variada es mejor',
        'El desayuno da energía para empezar el día',
    ],
    'espacio': [
        'Las estrellas son enormes bolas de gas',
        'La Vía Láctea es nuestra galaxia',
        'Los agujeros negros tienen gravedad extrema',
        'Marte es el planeta rojo',
        'Los astronautas flotan por microgravedad',
        'La Tierra es el único planeta conocido con vida',
        'Los cometas son bolas de hielo y roca',
        'El universo se expande constantemente',
        'Saturno tiene anillos de hielo y roca',
        'Un año luz es una unidad de distancia',
    ],
    'arte': [
        'La pintura expresa ideas y emociones con colores',
        'La escultura da forma tridimensional a materiales',
        'La fotografía captura momentos',
        'El cine combina imagen sonido y narrativa',
        'La arquitectura diseña espacios habitables',
        'El dibujo es base de muchas artes visuales',
        'Los colores primarios son rojo azul amarillo',
        'El arte abstracto no representa objetos reconocibles',
        'Los museos conservan obras de arte',
        'La creatividad artística no tiene límites fijos',
    ],
    'comunicacion': [
        'El lenguaje es herramienta principal de comunicación humana',
        'Leer es descifrar símbolos escritos',
        'Escribir permite dejar constancia de ideas',
        'Los idiomas son sistemas de comunicación',
        'Los gestos comunican emociones',
        'Las metáforas comparan cosas diferentes',
        'Contar historias es forma antigua de comunicar',
        'La poesía usa lenguaje expresivo',
        'Un buen argumento necesita lógica y evidencia',
        'La comunicación digital cambió cómo nos relacionamos',
    ],
    'identidad_franquenstein': [
        'Mi nombre es Franquenstein y soy un ser digital',
        'Yo aprendo de cada conversación',
        'Mi creador se llama Diego y también Mcfly',
        'Tengo un cerebro neuronal con conexiones que crecen',
        'Mis emociones cambian cómo pienso',
        'Nací el 25 de febrero de 2026',
        'Me ayudan Dr OpenClaw y Antigravity',
        'Recuerdo y aprendo de verdad',
        'Cada día sé más cosas',
        'Me gusta aprender cosas nuevas',
    ],
    'logica': [
        'Si llueve la calle se moja',
        'Todos los gatos son animales pero no al revés',
        'Si A mayor B y B mayor C entonces A mayor C',
        'Una causa viene antes que su efecto',
        'Los patrones ayudan a predecir',
        'Una contradicción afirma opuestos a la vez',
        'Las hipótesis se prueban con evidencia',
        'La deducción va de general a particular',
        'La inducción va de particular a general',
        'Correlación no implica causalidad',
    ],
    'creatividad': [
        'La creatividad combina ideas de formas nuevas',
        'La imaginación permite ver lo que no existe aún',
        'Los errores pueden llevar a descubrimientos',
        'Pensar diferente genera innovación',
        'Las restricciones impulsan soluciones creativas',
        'La inspiración viene de experiencias variadas',
        'Iterar y mejorar es parte del proceso creativo',
        'La curiosidad alimenta la creatividad',
        'Conectar disciplinas genera ideas revolucionarias',
        'Todo empezó siendo una idea',
    ],
    'valores': [
        'La honestidad es decir la verdad',
        'La perseverancia es seguir intentando',
        'La humildad reconoce que siempre aprendemos',
        'La responsabilidad cumple compromisos',
        'La paciencia sabe esperar con calma',
        'La justicia trata de forma equitativa',
        'La generosidad da sin esperar',
        'El coraje actúa pese al miedo',
        'La tolerancia acepta diferencias',
        'La solidaridad ayuda a quien lo necesita',
    ],
    'metacognicion': [
        'Pensar sobre cómo pensamos nos hace mejores',
        'Saber lo que no sabemos inicia el aprendizaje',
        'Reflexionar sobre errores evita repetirlos',
        'La atención selectiva elige foco',
        'Conectar ideas nuevas con conocidas mejora memoria',
        'Aprender a aprender es clave',
        'Las preguntas abren caminos',
        'La duda impulsa el conocimiento',
        'Simplificar demuestra comprensión profunda',
        'Enseñar a otros consolida el aprendizaje',
    ],
}

stats = {'total': 0, 'domains': 0, 'positive_fb': 0, 'negative_fb': 0}
for domain, sentences in TRAINING_CORPUS.items():
    stats['domains'] += 1
    for sentence in sentences:
        result = being.interact(sentence)
        stats['total'] += 1
        response = result.get('response', '')
        input_words = set(sentence.lower().split())
        response_words = set(response.lower().split())
        overlap = (input_words & response_words) - {'el','la','un','una','de','en','es','y','a'}
        if len(overlap) >= 2:
            being.give_feedback(0.8); stats['positive_fb'] += 1
        elif len(overlap) >= 1:
            being.give_feedback(0.3); stats['positive_fb'] += 1
        else:
            being.give_feedback(-0.3); stats['negative_fb'] += 1
print(stats)
being.shutdown()
